version: '3.9'

services:
  site:
    image: ${DOCKERHUB_USERNAME}/grdmad:${IMAGE_TAG}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"

        # HTTP -> HTTPS
        - "traefik.http.routers.grdmad-web.rule=Host(`grdmad.com.br`,`www.grdmad.com.br`)"
        - "traefik.http.routers.grdmad-web.entrypoints=web"
        - "traefik.http.routers.grdmad-web.middlewares=grdmad-https-redirect"
        - "traefik.http.middlewares.grdmad-https-redirect.redirectscheme.scheme=https"

        # HTTPS
        - "traefik.http.routers.grdmad-secure.rule=Host(`grdmad.com.br`,`www.grdmad.com.br`)"
        - "traefik.http.routers.grdmad-secure.entrypoints=websecure"
        - "traefik.http.routers.grdmad-secure.tls=true"
        - "traefik.http.routers.grdmad-secure.tls.certresolver=letsencryptresolver"

        # Porta interna (nginx serve na 80)
        - "traefik.http.services.grdmad.loadbalancer.server.port=80"

    volumes:
      - ./dist:/usr/share/nginx/html:ro

    networks:
      - network_public

networks:
  network_public:
    external: true
