version: "3.9"

services:
  site:
    image: ${DOCKERHUB_USERNAME}/grdmad:${IMAGE_TAG}

    # Sem ports e SEM volumes (sem bind-mount)
    networks:
      - traefik_public

    deploy:
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 30s
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"

        # HTTP -> HTTPS
        - "traefik.http.routers.grdmad-web.rule=Host(`grdmad.com.br`,`www.grdmad.com.br`)"
        - "traefik.http.routers.grdmad-web.entrypoints=web"
        - "traefik.http.routers.grdmad-web.middlewares=grdmad-https-redirect"
        - "traefik.http.middlewares.grdmad-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.middlewares.grdmad-https-redirect.redirectscheme.permanent=true"
        - "traefik.http.routers.grdmad-web.service=grdmad"

        # HTTPS
        - "traefik.http.routers.grdmad-secure.rule=Host(`grdmad.com.br`,`www.grdmad.com.br`)"
        - "traefik.http.routers.grdmad-secure.entrypoints=websecure"
        - "traefik.http.routers.grdmad-secure.tls=true"
        - "traefik.http.routers.grdmad-secure.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.grdmad-secure.service=grdmad"
        - "traefik.http.routers.grdmad-secure.tls.domains[0].main=grdmad.com.br"
        - "traefik.http.routers.grdmad-secure.tls.domains[0].sans=www.grdmad.com.br"

        # Porta interna do Nginx
        - "traefik.http.services.grdmad.loadbalancer.server.port=80"

networks:
  traefik_public:
    external: true
