name: CI/CD Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Define Image Tag
        id: meta
        run: echo "tag=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/grdmad:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/grdmad:${{ steps.meta.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-to-server:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: IMAGE_TAG,DOCKERHUB_USERNAME
          script: |
            IMAGE_TAG=${{ needs.build-and-push.outputs.image_tag }}
            DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}

            cd /var/www/grd-mad

            if [ ! -f docker-compose.yml ]; then
              echo "❌ docker-compose.yml não encontrado!"
              exit 1
            fi

            export IMAGE_TAG DOCKERHUB_USERNAME
            envsubst < docker-compose.yml > docker-compose.rendered.yml

            docker compose pull
            docker stack deploy -c docker-compose.rendered.yml grdmad

            docker image prune -f
            docker builder prune -f
